[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.11"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_DATABASE_URL,REACT_APP_ML_API_URL,REACT_APP_WS_URL"


